services:
  db_master:
    image: postgres:16
    container_name: insurance-postgres-master
    volumes:
      - postgres_master_data:/var/lib/postgresql/data/
      - ./insurance_recommendation_system/app/sql/init:/docker-entrypoint-initdb.d/
      - ./postgres/configs/master:/etc/postgresql/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=insurance
      - POSTGRES_DB=insurance
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U insurance" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  db_slave:
    image: postgres:16
    container_name: insurance-postgres-slave
    volumes:
      - postgres_slave_data:/var/lib/postgresql/data/
      - ./postgres/configs/slave:/etc/postgresql/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=insurance
      - POSTGRES_DB=insurance
    ports:
      - "5433:5432"
    depends_on:
      db_master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U insurance" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  app:
    build: ./insurance_recommendation_system
    container_name: insurance-api-service
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./insurance_recommendation_system:/app
      - ./migrations:/app/migrations
    ports:
      - "8000:8000"
    depends_on:
      db_master:
        condition: service_healthy
      recommendation_system:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://insurance:postgres@db_master:5432/insurance
      - DATABASE_SLAVE_URL=postgresql://insurance:postgres@db_slave:5432/insurance
      - RECOMMENDATION_API_URL=http://recommendation_system:8001/api/recommendations
      - PYTHONPATH=/app

  migration:
    build: ./insurance_recommendation_system
    container_name: insurance-db-migration
    command: tail -f /dev/null
    volumes:
      - ./insurance_recommendation_system:/app
      - ./migrations:/app/migrations
    depends_on:
      db_master:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://insurance:postgres@db_master:5432/insurance
      - PYTHONPATH=/app

  recommendation_system:
    build:
      context: ./recommendation_system
    container_name: insurance-ml-recommendation
    volumes:
      - ./recommendation_system:/app
    ports:
      - "8001:8001"
    environment:
      - MODEL_PATH=sentence-transformers/all-MiniLM-L6-v2
      - PRODUCTS_DATA_PATH=/app/model/products_data.json
      - PYTHONHTTPSVERIFY=0
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
      - DATABASE_URL=postgresql://insurance:postgres@db_master:5432/insurance
      - PYTHONPATH=/app
    command: >
      sh -c "python init_alembic.py &&
             python apply_migrations.py && 
             python watch_changes.py &
             uvicorn main:app --host 0.0.0.0 --port 8001 --reload --reload-dir /app"
    depends_on:
      db_master:
        condition: service_healthy

  replication_setup:
    image: postgres:16
    container_name: insurance-replication-setup
    volumes:
      - ./postgres/scripts:/scripts
    environment:
      - PGPASSWORD=postgres
    depends_on:
      db_master:
        condition: service_healthy
      db_slave:
        condition: service_healthy
    command: >
      sh -c "chmod +x /scripts/setup_replication.sh && 
             /scripts/setup_replication.sh"

volumes:
  postgres_master_data:
  postgres_slave_data: