services:
  db:
    image: postgres:16
    container_name: insurance-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./insurance_recommendation_system/app/sql/init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=insurance
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./insurance_recommendation_system
    container_name: backend-insurance-app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./insurance_recommendation_system:/app
      - ./migrations:/app/migrations
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      recommendation_system:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/insurance
      - RECOMMENDATION_API_URL=http://recommendation_system:8001/api/recommendations
      - PYTHONPATH=/app

  migration:
    build: ./insurance_recommendation_system
    container_name: db-migration-service
    command: tail -f /dev/null
    volumes:
      - ./insurance_recommendation_system:/app
      - ./migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/insurance
      - PYTHONPATH=/app

  recommendation_system:
    build:
      context: ./recommendation_system
    volumes:
      - ./recommendation_system:/app
    ports:
      - "8001:8001"
    environment:
      - MODEL_PATH=sentence-transformers/all-MiniLM-L6-v2
      - PRODUCTS_DATA_PATH=/app/model/products_data.json
      - PYTHONHTTPSVERIFY=0
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/insurance
      - PYTHONPATH=/app
    command: >
      sh -c "python init_alembic.py &&
             python apply_migrations.py && 
             python watch_changes.py &
             uvicorn main:app --host 0.0.0.0 --port 8001 --reload --reload-dir /app"
    depends_on:
      - db

volumes:
  postgres_data: