version: '3.8'

services:
  db:
    image: postgres:13
    container_name: insurance-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./insurance_recommendation_system/app/sql/init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=insurance
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./insurance_recommendation_system
    container_name: backend-insurance-app
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./insurance_recommendation_system:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      recommendation_system:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/insurance
      - EMAIL_HOST=smtp.yandex.ru
      - EMAIL_PORT=587
      - EMAIL_USERNAME=ilosipenko@edu.hse.ru
      - EMAIL_PASSWORD=mirjmgxpzrhyeapp
      - SECRET_KEY=549nc4eg=t92&)b)_ebhlpk)b8i)-ju6(8uqt*(g!8gi1fy8!
      - RECOMMENDATION_API_URL=http://recommendation_system:8001/api/recommendations

  recommendation_system:
    build: ./recommendation_system
    container_name: recommendation-system
    ports:
      - "8001:8001"
    volumes:
      - ./recommendation_system/model:/app/model
      - ./recommendation_system/model_cache:/app/model_cache
    environment:
      - MODEL_PATH=sentence-transformers/all-MiniLM-L6-v2
      - PRODUCTS_DATA_PATH=/app/model/products_data.json
      - PYTHONHTTPSVERIFY=0
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
    restart: unless-stopped

volumes:
  postgres_data:
